# SparrowProxy Configuration
http:
  addr: ":8080"

https:
  addr: ":8443"

# TLS certificates
tls:
- sni_hosts:
  - "example.com"
  - "*.example.com"
  cert_pem: |-
    -----BEGIN CERTIFICATE-----
    MIIEQTCCAymgAwIBAgIRAJdDN2MCmKwrHN9mxvR9/w4wDQYJKoZIhvcNAQELBQAw
    gZoxCzAJBgNVBAYTAkpQMQ4wDAYDVQQIEwVUb2t5bzENMAsGA1UEBxMESGlubzEW
    MBQGA1UEChMNQm9veWFoRGV2IExhYjEQMA4GA1UECxMHcHJpdmF0ZTEeMBwGA1UE
    AxMVQm9veWFoRGV2IExhYiBSb290IENBMSIwIAYJKoZIhvcNAQkBDBNtaXpvZnVt
    aUBib295YWguZGV2MB4XDTI1MDgwOTE0NTI0NloXDTM1MDgwOTE0NTI0NlowgZ4x
    CzAJBgNVBAYTAkpQMQ4wDAYDVQQIEwVUb2t5bzENMAsGA1UEBxMESGlubzEWMBQG
    A1UEChMNQm9veWFoRGV2IExhYjEQMA4GA1UECxMHcHJpdmF0ZTEiMCAGA1UEAxMZ
    cHJveG1veDAwMS50eWQuYm9veWFoLmRldjEiMCAGCSqGSIb3DQEJAQwTbWl6b2Z1
    bWlAYm9veWFoLmRldjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANY/
    bZW4ONX2BWyhUeT2kBmcJC5k0T4A/g3dUqZHMKHK76DajDI399HThEFAmvXmknEk
    CSkVoVQyVy1kwjdm5nd6tOkTy1W9sQeWRUmgS/NiiATzJxLGc5QIj+d17Crhn3Oz
    iPhNxGketM4sO7iQ3kP18RGML+Qhw93VJqoIw19bKU2GSLqDzFjC+Zgh28v7MZde
    HrkcYU4Qpi0KhY1oAMAmDVwcsGgITTM/oRAMqDJygbgEWrllo0kUnfOmPoL9O2pd
    3fauIYEtQbkzwlR2UajDI4yuiQE2Trb1RsCMMTHHTxMwjfOf4Eo8TORo0/Gh3M2b
    lgBFlgjTqR9Z3A/zWhECAwEAAaN8MHowDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQM
    MAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUm1hZOiVGt3r3
    NsfPjNEbLOZeSHowJAYDVR0RBB0wG4IZcHJveG1veDAwMS50eWQuYm9veWFoLmRl
    djANBgkqhkiG9w0BAQsFAAOCAQEAkFPkLTo5GsVJZOam7q6Oeh8La2HoI6ijfoeG
    Xfs3xdfvdLgHq6hX72Kcyo6n8gQR4vy4xzu75mYQqi4kMZrGE3hEoZlPi/PMaY5M
    Ly0bzxMu6tcA0GzKBFOAmrMac8/iv8Kr9qA0mVhbWvmmDxU6u8eGKoJb5isTkqb4
    q/pPCmeKiMIjviBT8Xfnr8bgPZPjwYtyjyqnSysALfAcqgSp9YHESpco5GTTNGT4
    z0Oscz2Yg7ihCLlw/F4jUGghAeAF4/JAEPIKIOosXRF22gk3WMj0vXXWGaQo403Z
    QwiBXkVZc4uw4601wXmtCicP0gKpMlmlQdeAg6J39Tt6plJ3JQ==
    -----END CERTIFICATE-----

  key_pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA1j9tlbg41fYFbKFR5PaQGZwkLmTRPgD+Dd1SpkcwocrvoNqM
    Mjf30dOEQUCa9eaScSQJKRWhVDJXLWTCN2bmd3q06RPLVb2xB5ZFSaBL82KIBPMn
    EsZzlAiP53XsKuGfc7OI+E3EaR60ziw7uJDeQ/XxEYwv5CHD3dUmqgjDX1spTYZI
    uoPMWML5mCHby/sxl14euRxhThCmLQqFjWgAwCYNXBywaAhNMz+hEAyoMnKBuARa
    uWWjSRSd86Y+gv07al3d9q4hgS1BuTPCVHZRqMMjjK6JATZOtvVGwIwxMcdPEzCN
    85/gSjxM5GjT8aHczZuWAEWWCNOpH1ncD/NaEQIDAQABAoIBAAjrCvy4dmUxoHgt
    HuOQ/96RCVCFEdCq6ehZ1h7lx7h0YhUoA73zZnVtgIvWzJx/xIjBH0B+jgCbN9XD
    4/G6bs16Zh1tnYEsLDpMnwW5jm/LIi5SkMXPTPBUiujvl60RRznht0nestZNWOlc
    HgBIx3e8vRQl6bhtT2HkhX9+beOCLGbQXinhMiyaUho3BGciV7a8m5KBSDszgNHI
    HhB5d9RD5djtq4GhhH9i8T6VJXOXbnE6GN07lYwSivIwfpoYNCi+Z4v6kUv30uCZ
    AUVm96T3v0zLagirK0OqK5Mo/kmda7kCav6VOPUXusb9sQPIu4wkP7k05vSKhskc
    HflXnYECgYEA3Wqij2eVgOyz4DYWg9cGB+7n89EX8C025Hs81G1Wyrcgltrb/Rpg
    QHMADFsbZe9/kbgJBO4wbPc7m20lvV8DFZcP2wfd46KuYun7vnXkmNdRtpwdkq5L
    ctdTRs/vTYYm+n83mnBJNa6U5rw2cA+vtcSRM+Vq6hvYXX+HEm12kQ0CgYEA97Ym
    EnNFv/4Htpx/FhDaPpPJSESnGB7/qq02DulOviFyHveJ2yhmKTGpYAMrb/ysLX+O
    SFftobTvn7w7XNzFAnO4lpqIbU1/urwWDod2ONMAakLkZ00sjeghsh06aE4v+GKZ
    O31P8/ZtmtQSG6x62UCdKgnnazorB7eTD7D6RBUCgYEAnkThGlzSsyt/kF9ZTLhg
    6T7OsqvdzqKjQEMPQlE93v1z4CFlatB1yNvrRunA9eZya7j/SXTxTJKVGw60EV9f
    Fwm6HbjL1TGuMapLduNSmiYflMaXJQhNijN8pXtw9RtVtW1GU7C7xBGdAim7R/MO
    iIGPwWbWO63XxU2pQXTZcekCgYEAwQ6IK5cFhHWyg0MC1Sq7PUwm8pj29ZirP9UR
    LZvtz8b3T2UzXsfknzRiQj8WKohtlGQ2evF0dbQzkXW9eklhjeCsu0ujCjT9WIbg
    VeCDZhQk3axWoKAIGm0RXeTjsYlGX7pQnIm0t3mWwLWJi2HouMtf8fSYFPzXroMH
    LZKL6mUCgYEAh6rC1kbNW9J3KlHzzMD23ni97cRmPqCLI4L39UI1TQhY1gN9rcu1
    epwG8/3DQDopmrGjyn5SwY1hnB8t6zslUNm4T5Ba78JKT4s+84Rmpe08W2qRl4xR
    A/UUEuy8YcWQm50upH8jvVzRwWNFxw46E4tuCqRiHZHXS4//2MW+0NI=
    -----END RSA PRIVATE KEY-----
  # cert_path: "/app/certs/example.crt"
  # key_path: "/app/certs/example.key"

  # Services configuration
services:
- name: "web-service"
  hosts:
  - "example.com"
  - "www.example.com"
  routes:
  - "/"
  upstreams:
  - url: "http://backend1:8080"
  - url: "http://backend2:8080"
  health_check:
    path: "/health"
    interval: "10s"
    timeout: "5s"
  pass_host_header: true
  circuit_breaker:
    max_failures: 3
    recovery_time: "10s"
  retry:
    max_retries: 2

# Redirect rules
redirects:
- from_host: "old.example.com"
  to: "https://example.com"
  status_code: 301
