apiVersion: v1
kind: Secret
metadata:
  name: sparrowproxy-config
  namespace: default
type: Opaque
data:
  # Base64エンコードされたGitHub Personal Access Token
  # 以下は例です - 実際の値に置き換えてください
  # echo -n "ghp_your_personal_access_token_here" | base64
  github-token: Z2hwX3lvdXJfcGVyc29uYWxfYWNjZXNzX3Rva2VuX2hlcmU=
