apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparrowproxy
  namespace: default
  labels:
    app: sparrowproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparrowproxy
  template:
    metadata:
      labels:
        app: sparrowproxy
    spec:
      containers:
      - name: sparrowproxy
        # GitHub Actionsでビルド・プッシュされるイメージ
        image: docker-registry.booyah.dev/sparrowproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8000
          name: health
          protocol: TCP
        env:
        - name: CONFIG_REPO_URL
          value: "https://github.com/BooyahDev/SparrowProxyConfig.git"
        - name: CONFIG_REPO_PATH
          value: "/app/config-repo"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: sparrowproxy-config
              key: github-token
        volumeMounts:
        - name: config-repo-volume
          mountPath: /app/config-repo
        # リソース制限（開発環境用）
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # セキュリティ設定
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        # ヘルスチェック
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config-repo-volume
        emptyDir: {}
      restartPolicy: Always
