apiVersion: v1
kind: Secret
metadata:
  name: sparrowproxy-config
  namespace: default
type: Opaque
data:
  # Base64エンコードされたSSH秘密鍵（GitリポジトリアクセスのためのSSHキー）
  # 以下は例です - 実際の値に置き換えてください
  # echo -n "$(cat ~/.ssh/id_ed25519)" | base64
  #ssh-private-key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBZm1xblVNTzJxeTFZOTdOYjZOYTlRQU1rQnFSdlJoNWhkdGpXTkNBTERBQUFBSWhVTThObFZEUERaClZRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWZtcW5VTU8ycXkxWTk3TmI2TmE5UUFNa0JxUnZSaDVoZHRqV05DQUxEQUEKQUFBZ0R3eXJCWTliNXB6NE9JNHhXcnlSTUx0azZZdGNHQjBiS2xHTzhTRERiTzBBQUFBRGJXbDZiMloxYldsQWFHOTBiUwpGaWJHOWlZV3d1WTI5dEFRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: sparrowproxy-ssh-config
  namespace: default
type: Opaque
data:
  # SSH設定ファイル（GitHub用のknown_hosts設定等）
  # echo -n "$(cat ~/.ssh/known_hosts | grep github.com)" | base64
  #known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSVdBQUtRWVVFTjhRWnlGSFRMSys3N2lpaWNZQWNEUytaSGtDNXp3dFM3MGFjUTVvSHBLM2hsMUhDOWpWbjlLaG9yRTB1VW1SSUZJNGNBdUQ4VmVqUndnM0V6bHE4TCtKUkwxR1FsbHVGMi9rbytpV1B6UHo1YjBLbm5JN21JNkNvYWVSRnFQZ2FNS2E3TlFoQVFFRklOQTNTcVIrNVJ4VEdCU2p1M2g3WVRuTnZYenFQclFqYjBBQUFBQUE9
